import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { parse, type Tags } from 'yaml';

import { cmdInit } from '../src/commands/init.js';
import { ExitCode } from '../src/exit-codes.js';
import type { CliIO } from '../src/io.js';
import type { CheckboxChoice, Prompter, SelectChoice } from '../src/prompter.js';

function captureIO(): { io: CliIO; stdout: () => string; stderr: () => string } {
  const out: string[] = [];
  const err: string[] = [];
  return {
    io: { out: (t) => out.push(t), err: (t) => err.push(t) },
    stdout: () => out.join(''),
    stderr: () => err.join(''),
  };
}

interface ScriptedAnswers {
  readonly inputs?: ReadonlyArray<string | undefined>;
  readonly passwords?: ReadonlyArray<string>;
  readonly confirms?: ReadonlyArray<boolean>;
  readonly selects?: ReadonlyArray<unknown>;
  readonly checkboxes?: ReadonlyArray<readonly unknown[]>;
}

/**
 * Fake prompter that pulls answers off four FIFO queues. Test code
 * declares the expected answer order; deviation throws so a missed
 * prompt or extra prompt surfaces clearly.
 */
function fakePrompter(answers: ScriptedAnswers): Prompter {
  const inputs = [...(answers.inputs ?? [])];
  const passwords = [...(answers.passwords ?? [])];
  const confirms = [...(answers.confirms ?? [])];
  const selects = [...(answers.selects ?? [])];
  const checkboxes = [...(answers.checkboxes ?? [])];
  function take<T>(queue: T[], kind: string): T {
    if (queue.length === 0) throw new Error(`fakePrompter: out of ${kind} answers`);
    return queue.shift()!;
  }
  return {
    async input(opts) {
      const a = take(inputs, 'input');
      return a ?? opts.default ?? '';
    },
    async password() {
      return take(passwords, 'password');
    },
    async confirm() {
      return take(confirms, 'confirm');
    },
    async select<T>(_opts: {
      readonly message: string;
      readonly choices: ReadonlyArray<SelectChoice<T>>;
      readonly default?: T;
    }): Promise<T> {
      return take(selects, 'select') as T;
    },
    async checkbox<T>(_opts: {
      readonly message: string;
      readonly choices: ReadonlyArray<CheckboxChoice<T>>;
    }): Promise<readonly T[]> {
      return take(checkboxes, 'checkbox') as readonly T[];
    },
  };
}

const tmpDirs: string[] = [];

afterEach(async () => {
  await Promise.all(
    tmpDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })),
  );
});

async function inTmp(): Promise<string> {
  const d = await mkdtemp(join(tmpdir(), 'fs-init-'));
  tmpDirs.push(d);
  return d;
}

const envTag: Tags[number] = {
  tag: '!env',
  resolve(name: string): string {
    return `__ENV__${name.trim()}`;
  },
};

describe('framescout init', () => {
  it('writes a valid config.yaml from a minimal MQTT-only flow', async () => {
    const dir = await inTmp();
    const cfgPath = join(dir, 'config.yaml');
    const r = captureIO();
    const prompter = fakePrompter({
      inputs: [
        'garden', // deploymentId
        'front-yard', // cameraId
        'https://192.0.2.50', // hub baseUrl
        'admin', // hub username
        '0', // channel
        '15000', // pollIntervalMs
        'http://localhost:8001', // megadetector endpoint
        'mqtt://homeassistant.local', // mqtt brokerUrl
        'framescout/{deployment}/{camera}', // mqtt topic
        '/var/lib/framescout/audit', // ndjson path
      ],
      passwords: ['letmein'],
      confirms: [],
      selects: ['@framescout/source-reolink-hub'],
      checkboxes: [
        ['@framescout/detector-megadetector-http'],
        ['@framescout/sink-mqtt', '@framescout/sink-file-ndjson'],
      ],
    });

    const code = await cmdInit({ path: cfgPath }, r.io, prompter);
    expect(code).toBe(ExitCode.Success);

    const written = await readFile(cfgPath, 'utf-8');
    // The banner comment should be there.
    expect(written).toContain('Generated by `framescout init`');
    // Secrets are referenced by env-var name with the keys the plugins'
    // config schemas accept (the daemon rejects `password:` for the hub).
    expect(written).toMatch(/passwordEnv: REOLINK_PASSWORD/);
    expect(written).toMatch(/apiKeyEnv: MEGADETECTOR_API_KEY/);
    expect(written).toMatch(/usernameEnv: MQTT_USERNAME/);
    expect(written).not.toMatch(/^\s*(password|apiKey|bearerTokenEnv):/m);

    // And the file round-trips through the parser the daemon uses.
    const parsed = parse(written, { customTags: [envTag] }) as Record<string, unknown>;
    expect(parsed.deployments).toEqual([
      { id: 'garden', cameras: [{ id: 'front-yard' }] },
    ]);
    expect(parsed.sources).toHaveLength(1);
    expect(parsed.detectors).toHaveLength(1);
    expect(parsed.sinks).toHaveLength(2);

    // The companion .env.example was created next to the config file.
    const envExample = await readFile(join(dir, '.env.example'), 'utf-8');
    expect(envExample).toMatch(/REOLINK_PASSWORD=/);
    expect(envExample).toMatch(/MEGADETECTOR_API_KEY=/);
    expect(envExample).toMatch(/MQTT_USERNAME=/);
  });

  it('references bearer tokens with the keys the webhook and multipart sinks accept', async () => {
    const dir = await inTmp();
    const cfgPath = join(dir, 'config.yaml');
    const r = captureIO();
    const prompter = fakePrompter({
      inputs: [
        'garden',
        'front-yard',
        'https://192.0.2.50',
        'admin',
        '0',
        '15000',
        'http://localhost:8001', // megadetector endpoint
        'https://hooks.example.com/framescout', // webhook url
        'https://ingest.example.com/api/ingest', // multipart endpoint
      ],
      passwords: ['x'],
      selects: ['@framescout/source-reolink-hub', 'bulletin-v1'],
      checkboxes: [
        ['@framescout/detector-megadetector-http'],
        ['@framescout/sink-webhook', '@framescout/sink-http-multipart'],
      ],
    });

    const code = await cmdInit({ path: cfgPath }, r.io, prompter);
    expect(code).toBe(ExitCode.Success);

    const written = await readFile(cfgPath, 'utf-8');
    expect(written).toMatch(/bearerEnv: WEBHOOK_BEARER/);
    expect(written).toMatch(/bearerEnv: HTTP_MULTIPART_BEARER/);
    expect(written).toMatch(/wireFormat: bulletin-v1/);
    expect(written).not.toMatch(/bearerTokenEnv/);
  });

  it('aborts when the operator declines the DeepFaune NC license', async () => {
    const dir = await inTmp();
    const cfgPath = join(dir, 'config.yaml');
    const r = captureIO();
    const prompter = fakePrompter({
      inputs: [
        'home',
        'cam',
        'https://192.0.2.50',
        'admin',
        '0',
        '15000',
        'http://localhost:8001', // megadetector endpoint
        // (no deepfaune endpoint — we abort first)
      ],
      passwords: ['x'],
      confirms: [false], // decline the NC banner
      selects: ['@framescout/source-reolink-hub'],
      checkboxes: [
        [
          '@framescout/detector-megadetector-http',
          '@framescout/detector-deepfaune-http',
        ],
      ],
    });

    const code = await cmdInit({ path: cfgPath }, r.io, prompter);
    expect(code).toBe(ExitCode.Misuse);
    expect(r.stderr()).toContain('non-commercial');
    // No file written.
    await expect(readFile(cfgPath, 'utf-8')).rejects.toThrow();
  });

  it('refuses to overwrite an existing file unless the user confirms', async () => {
    const dir = await inTmp();
    const cfgPath = join(dir, 'config.yaml');
    await writeFile(cfgPath, '# existing content\n', 'utf-8');
    const r = captureIO();
    const prompter = fakePrompter({
      confirms: [false], // decline overwrite
    });
    const code = await cmdInit({ path: cfgPath }, r.io, prompter);
    expect(code).toBe(ExitCode.Success);
    expect(r.stdout()).toContain('init aborted');
    expect(await readFile(cfgPath, 'utf-8')).toBe('# existing content\n');
  });

  it('--force overwrites without asking', async () => {
    const dir = await inTmp();
    const cfgPath = join(dir, 'config.yaml');
    await writeFile(cfgPath, '# existing\n', 'utf-8');
    const r = captureIO();
    const prompter = fakePrompter({
      inputs: [
        'g',
        'c',
        'https://h.example/',
        'admin',
        '0',
        '15000',
        'http://localhost:8001',
        'mqtt://broker.example/',
        'fs/{deployment}/{camera}',
        '/var/lib/framescout/audit',
      ],
      passwords: ['p'],
      selects: ['@framescout/source-reolink-hub'],
      checkboxes: [
        ['@framescout/detector-megadetector-http'],
        ['@framescout/sink-mqtt', '@framescout/sink-file-ndjson'],
      ],
    });
    const code = await cmdInit({ path: cfgPath, force: true }, r.io, prompter);
    expect(code).toBe(ExitCode.Success);
    expect(await readFile(cfgPath, 'utf-8')).toContain('Generated by `framescout init`');
  });

  it('refuses to write a config without any sink', async () => {
    const dir = await inTmp();
    const cfgPath = join(dir, 'config.yaml');
    const r = captureIO();
    const prompter = fakePrompter({
      inputs: [
        'home',
        'cam',
        'https://192.0.2.50',
        'admin',
        '0',
        '15000',
        'http://localhost:8001',
      ],
      passwords: ['x'],
      selects: ['@framescout/source-reolink-hub'],
      checkboxes: [
        ['@framescout/detector-megadetector-http'],
        [], // no sinks selected
      ],
    });
    const code = await cmdInit({ path: cfgPath }, r.io, prompter);
    expect(code).toBe(ExitCode.Misuse);
    expect(r.stderr()).toContain('at least one sink');
  });
});
